In [1]:
import pandas as pd

In [2]:
mvp = pd.read_csv('mvps_data.csv')

In [3]:
mvp.head()

,Unnamed: 0,Rank,Player,Age,Tm,First,Pts Won,Pts Max,Share,G,...,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48,year
0,0,1,Michael Jordan,27,CHI,77.0,891.0,960,0.928,82,...,6.0,5.5,2.7,1.0,0.539,0.312,0.851,20.3,0.321,1991
1,1,2,Magic Johnson,31,LAL,10.0,497.0,960,0.518,79,...,7.0,12.5,1.3,0.2,0.477,0.320,0.906,15.4,0.251,1991
2,2,3,David Robinson,25,SAS,6.0,476.0,960,0.496,82,...,13.0,2.5,1.5,3.9,0.552,0.143,0.762,17.0,0.264,1991
3,3,4,Charles Barkley,27,PHI,2.0,222.0,960,0.231,67,...,10.1,4.2,1.6,0.5,0.570,0.284,0.722,13.4,0.258,1991
4,4,5,Karl Malone,27,UTA,0.0,142.0,960,0.148,82,...,11.8,3.3,1.1,1.0,0.527,0.286,0.770,15.5,0.225,1991

In [5]:
mvp  = mvp[["Player", "year", "Pts Won", "Pts Max", "Share"]]

In [6]:
mvp

                Player  year  Pts Won  Pts Max  Share
0       Michael Jordan  1991    891.0      960  0.928
1        Magic Johnson  1991    497.0      960  0.518
2       David Robinson  1991    476.0      960  0.496
3      Charles Barkley  1991    222.0      960  0.231
4          Karl Malone  1991    142.0      960  0.148
..                 ...   ...      ...      ...    ...
469  Russell Westbrook  2021      5.0     1010  0.005
470        Ben Simmons  2021      3.0     1010  0.003
471       James Harden  2021      1.0     1010  0.001
472       LeBron James  2021      1.0     1010  0.001
473      Kawhi Leonard  2021      1.0     1010  0.001

[474 rows x 5 columns]

In [10]:
players = pd.read_csv("players_data.csv")

In [11]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18044 entries, 0 to 18043
Data columns (total 32 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  18044 non-null  int64
 1   Rk          18044 non-null  object
 2   Player      18044 non-null  object
 3   Pos         18044 non-null  object
 4   Age         18044 non-null  object
 5   Tm          18044 non-null  object
 6   G           18044 non-null  object
 7   GS          18044 non-null  object
 8   MP          18044 non-null  object
 9   FG          18044 non-null  object
 10  FGA         18044 non-null  object
 11  FG%         17953 non-null  object
 12  3P          18044 non-null  object
 13  3PA         18044 non-null  object
 14  3P%         15260 non-null  object
 15  2P          18044 non-null  object
 16  2PA         18044 non-null  object
 17  2P%         17896 non-null  object
 18  eFG%        17953 non-null  object
 19  FT          18044 non-null  object
 20  FTA         18044 non-null  object
 21  FT%         17250 non-null  object
 22  ORB         18044 non-null  object
 23  DRB         18044 non-null  object
 24  TRB         18044 non-null  object
 25  AST         18044 non-null  object
 26  STL         18044 non-null  object
 27  BLK         18044 non-null  object
 28  TOV         18044 non-null  object
 29  PF          18044 non-null  object
 30  PTS         18044 non-null  object
 31  Year        18044 non-null  int64
dtypes: int64(2), object(30)
memory usage: 4.4+ MB

In [12]:
del players["Unnamed: 0"]
del players["Rk"]

In [14]:
players["Player"] = players["Player"].str.replace("*","", regex=False)

In [15]:
players[players["Player"] == "Greg Anderson"]

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
8,Greg Anderson,PF,26,TOT,68,2,13.6,1.7,4.0,.430,...,1.4,3.3,4.7,0.2,0.5,0.7,1.2,2.1,4.3,1991
9,Greg Anderson,PF,26,MIL,26,0,9.5,1.0,2.8,.370,...,1.0,1.9,2.9,0.1,0.3,0.3,0.8,1.1,2.7,1991
10,Greg Anderson,PF,26,NJN,1,0,18.0,4.0,4.0,1.000,...,4.0,2.0,6.0,1.0,2.0,0.0,1.0,4.0,8.0,1991
11,Greg Anderson,PF,26,DEN,41,2,16.1,2.1,4.7,.440,...,1.6,4.1,5.8,0.3,0.6,0.9,1.5,2.6,5.2,1991
467,Greg Anderson,PF,27,DEN,82,82,34.1,4.7,10.4,.456,...,4.1,7.4,11.5,1.0,1.1,0.8,2.5,3.2,11.5,1992
1412,Greg Anderson,PF,29,DET,77,47,21.1,2.6,4.8,.543,...,2.4,5.0,7.4,0.7,0.7,0.9,1.2,3.0,6.4,1994
1911,Greg Anderson,PF,30,ATL,51,0,12.2,1.1,2.0,.548,...,1.2,2.5,3.7,0.3,0.5,0.6,0.6,2.0,2.9,1995
2381,Greg Anderson,PF,31,SAS,46,7,7.5,0.5,1.0,.511,...,0.6,1.5,2.2,0.2,0.2,0.5,0.5,1.4,1.2,1996
2948,Greg Anderson,C,32,SAS,82,48,20.2,1.6,3.2,.496,...,1.9,3.5,5.5,0.4,0.8,0.8,0.9,2.7,3.9,1997
3541,Greg Anderson,C,33,ATL,50,0,8.0,0.7,1.6,.444,...,0.8,1.6,2.4,0.3,0.4,0.2,0.3,1.7,1.8,1998

In [23]:
players.tail()

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
18039,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,.462,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
18040,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,.559,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
18041,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,.438,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
18042,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,.559,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
18043,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,.652,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021

In [24]:
players.shape[0]

18044

In [ ]:
players.groupby(["Player", "Year"]).get_group('')

In [ ]:
def single_team(df):
    if df.shape[0]==1:
        return df
    else:
        row = df[df["Tm"]=="TOT"]
        row["Tm"] = df.iloc[-1,:]["Tm"]
        return row

players = players.groupby(["Player", "Year"]).apply(single_team)

In [25]:
players

,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Year
0,Alaa Abdelnaby,PF,22,POR,43,0,6.7,1.3,2.7,.474,...,0.6,1.4,2.1,0.3,0.1,0.3,0.5,0.9,3.1,1991
1,Mahmoud Abdul-Rauf,PG,21,DEN,67,19,22.5,6.2,15.1,.413,...,0.5,1.3,1.8,3.1,0.8,0.1,1.6,2.2,14.1,1991
2,Mark Acres,C,28,ORL,68,0,19.3,1.6,3.1,.509,...,2.1,3.2,5.3,0.4,0.4,0.4,0.6,3.2,4.2,1991
3,Michael Adams,PG,28,DEN,66,66,35.5,8.5,21.5,.394,...,0.9,3.0,3.9,10.5,2.2,0.1,3.6,2.5,26.5,1991
4,Mark Aguirre,SF,31,DET,78,13,25.7,5.4,11.7,.462,...,1.7,3.1,4.8,1.8,0.6,0.3,1.6,2.7,14.2,1991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18039,Delon Wright,PG,28,SAC,27,8,25.8,3.9,8.3,.462,...,1.0,2.9,3.9,3.6,1.6,0.4,1.3,1.1,10.0,2021
18040,Thaddeus Young,PF,32,CHI,68,23,24.3,5.4,9.7,.559,...,2.5,3.8,6.2,4.3,1.1,0.6,2.0,2.2,12.1,2021
18041,Trae Young,PG,22,ATL,63,63,33.7,7.7,17.7,.438,...,0.6,3.3,3.9,9.4,0.8,0.2,4.1,1.8,25.3,2021
18042,Cody Zeller,C,28,CHO,48,21,20.9,3.8,6.8,.559,...,2.5,4.4,6.8,1.8,0.6,0.4,1.1,2.5,9.4,2021
18043,Ivica Zubac,C,23,LAC,72,33,22.3,3.6,5.5,.652,...,2.6,4.6,7.2,1.3,0.3,0.9,1.1,2.6,9.0,2021